Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -17,5 +17,9 @@ jobs:
       - run:
           name: scan image
           command: |
-            ./twistcli images scan --details --address $TL_URL -u $tl_u -p $tl_p --ci $TL_IMAGE":"$CIRCLE_BUILD_NUM
-
+            ./twistcli images scan --details --address $TL_URL -u $tl_u -p $tl_p --ci $TL_IMAGE":"$CIRCLE_BUILD_NUM | tee result.out
+            e=`cat result.out | grep -c "Scan failed due to"`
+            if [ $e -gt 0 ]; then
+              echo "Build failed"
+              exit 1
+            fi
